# Generated by Django 5.1.5 on 2025-03-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_operationlog_operation_type_inventorycheck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='member',
            name='purchase_count',
            field=models.IntegerField(default=0, verbose_name='消费次数'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('', '无颜色'), ('black', '黑色'), ('white', '白色'), ('red', '红色'), ('blue', '蓝色'), ('green', '绿色'), ('yellow', '黄色'), ('purple', '紫色'), ('grey', '灰色'), ('pink', '粉色'), ('orange', '橙色'), ('brown', '棕色'), ('other', '其他')], default='', max_length=20, verbose_name='颜色'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('', '无尺码'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('other', '其他')], default='', max_length=10, verbose_name='尺码'),
        ),
    ]
