# Generated by Django 5.1.5 on 2025-03-24 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0003_member_gender_member_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200, verbose_name='制造商'),
        ),
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.CharField(blank=True, max_length=200, verbose_name='规格'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='actual_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='实际售价'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='标准售价'),
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('SALE', '销售'), ('INVENTORY', '库存调整'), ('MEMBER', '会员管理'), ('OTHER', '其他')], max_length=20, verbose_name='操作类型')),
                ('details', models.TextField(verbose_name='操作详情')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('related_object_id', models.PositiveIntegerField(verbose_name='关联对象ID')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='操作员')),
                ('related_content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='关联类型')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-timestamp'],
            },
        ),
    ]
