# Generated by Django 5.1.5 on 2025-03-27 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_member_name_alter_member_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationlog',
            name='operation_type',
            field=models.CharField(choices=[('SALE', '销售'), ('INVENTORY', '库存调整'), ('MEMBER', '会员管理'), ('INVENTORY_CHECK', '库存盘点'), ('OTHER', '其他')], max_length=20, verbose_name='操作类型'),
        ),
        migrations.CreateModel(
            name='InventoryCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='盘点名称')),
                ('description', models.TextField(blank=True, verbose_name='盘点描述')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('in_progress', '盘点中'), ('completed', '已完成'), ('approved', '已审核'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_checks_approved', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_checks_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '库存盘点',
                'verbose_name_plural': '库存盘点',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.IntegerField(verbose_name='系统数量')),
                ('actual_quantity', models.IntegerField(blank=True, null=True, verbose_name='实际数量')),
                ('difference', models.IntegerField(blank=True, null=True, verbose_name='差异')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='盘点时间')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='盘点人')),
                ('inventory_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventorycheck', verbose_name='盘点单')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '盘点项目',
                'verbose_name_plural': '盘点项目',
                'unique_together': {('inventory_check', 'product')},
            },
        ),
    ]
