# Generated by Django 5.1.5 on 2025-03-29 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_member_birthday_member_purchase_count_product_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='notes',
            new_name='remark',
        ),
        migrations.RemoveField(
            model_name='member',
            name='notes',
        ),
        migrations.AddField(
            model_name='member',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='账户余额'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_recharged',
            field=models.BooleanField(default=False, verbose_name='是否充值会员'),
        ),
        migrations.AddField(
            model_name='sale',
            name='balance_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='余额支付'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', '现金'), ('wechat', '微信'), ('alipay', '支付宝'), ('card', '银行卡'), ('balance', '账户余额'), ('mixed', '混合支付'), ('other', '其他')], default='cash', max_length=20, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=100, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实付金额'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.member', verbose_name='会员'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作员'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总金额'),
        ),
        migrations.CreateModel(
            name='RechargeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='充值金额')),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实收金额')),
                ('payment_method', models.CharField(choices=[('cash', '现金'), ('wechat', '微信'), ('alipay', '支付宝'), ('card', '银行卡'), ('other', '其他')], max_length=20, verbose_name='支付方式')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='充值时间')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharge_records', to='inventory.member', verbose_name='会员')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作员')),
            ],
            options={
                'verbose_name': '充值记录',
                'verbose_name_plural': '充值记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
