# Generated by Django 5.2 on 2025-04-24 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_rename_notes_sale_remark_remove_member_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='颜色名称')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='颜色代码')),
            ],
            options={
                'verbose_name': '颜色',
                'verbose_name_plural': '颜色',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='尺码名称')),
            ],
            options={
                'verbose_name': '尺码',
                'verbose_name_plural': '尺码',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店铺名称')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='地址')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '店铺',
                'verbose_name_plural': '店铺',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='供应商名称')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='电子邮件')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='我的商店', max_length=100, verbose_name='公司名称')),
                ('company_address', models.TextField(blank=True, null=True, verbose_name='公司地址')),
                ('company_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='电子邮箱')),
                ('company_website', models.URLField(blank=True, null=True, verbose_name='网站')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='公司标志')),
                ('barcode_width', models.IntegerField(default=300, verbose_name='条码宽度')),
                ('barcode_height', models.IntegerField(default=100, verbose_name='条码高度')),
                ('barcode_font_size', models.IntegerField(default=12, verbose_name='条码字体大小')),
                ('barcode_show_price', models.BooleanField(default=True, verbose_name='显示价格')),
                ('barcode_show_name', models.BooleanField(default=True, verbose_name='显示商品名称')),
                ('barcode_show_company', models.BooleanField(default=True, verbose_name='显示公司名称')),
                ('receipt_header', models.TextField(blank=True, null=True, verbose_name='小票页眉')),
                ('receipt_footer', models.TextField(blank=True, null=True, verbose_name='小票页脚')),
                ('enable_low_stock_alert', models.BooleanField(default=True, verbose_name='启用低库存提醒')),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='默认税率')),
                ('currency_symbol', models.CharField(default='¥', max_length=10, verbose_name='货币符号')),
                ('timezone', models.CharField(default='Asia/Shanghai', max_length=50, verbose_name='时区')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
            },
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'permissions': (('can_view_item', '可以查看物料'), ('can_add_item', '可以添加物料'), ('can_change_item', '可以修改物料'), ('can_delete_item', '可以删除物料'), ('can_export_item', '可以导出物料'), ('can_import_item', '可以导入物料'), ('can_allocate_item', '可以分配物料'), ('can_checkin_item', '可以入库物料'), ('can_checkout_item', '可以出库物料'), ('can_adjust_item', '可以调整物料库存'), ('can_return_item', '可以归还物料'), ('can_move_item', '可以移动物料'), ('can_manage_backup', '可以管理备份')), 'verbose_name': '库存', 'verbose_name_plural': '库存'},
        ),
        migrations.AlterModelOptions(
            name='memberlevel',
            options={'ordering': ['priority', 'points_threshold'], 'verbose_name': '会员等级', 'verbose_name_plural': '会员等级'},
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='member',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_members', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否活跃'),
        ),
        migrations.AddField(
            model_name='member',
            name='member_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='会员号'),
        ),
        migrations.AddField(
            model_name='member',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='member',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_members', to=settings.AUTH_USER_MODEL, verbose_name='更新人'),
        ),
        migrations.AddField(
            model_name='memberlevel',
            name='color',
            field=models.CharField(default='blue', max_length=50, verbose_name='颜色标识'),
        ),
        migrations.AddField(
            model_name='memberlevel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='memberlevel',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='是否默认等级'),
        ),
        migrations.AddField(
            model_name='memberlevel',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='优先级'),
        ),
        migrations.CreateModel(
            name='MemberTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PURCHASE', '消费'), ('REFUND', '退款'), ('RECHARGE', '充值'), ('POINTS_EARN', '积分奖励'), ('POINTS_REDEEM', '积分兑换'), ('POINTS_ADJUST', '积分调整'), ('BALANCE_ADJUST', '余额调整'), ('LEVEL_UPGRADE', '等级升级'), ('LEVEL_DOWNGRADE', '等级降级'), ('OTHER', '其他')], max_length=20, verbose_name='交易类型')),
                ('points_change', models.IntegerField(default=0, verbose_name='积分变动')),
                ('balance_change', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='余额变动')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='交易时间')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='关联对象ID')),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='关联对象类型')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_transactions', to=settings.AUTH_USER_MODEL, verbose_name='操作员')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.member', verbose_name='会员')),
            ],
            options={
                'verbose_name': '会员交易记录',
                'verbose_name_plural': '会员交易记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='图片')),
                ('thumbnail', models.CharField(blank=True, max_length=255, null=True, verbose_name='缩略图路径')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='替代文本')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否主图')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_stock', '低库存'), ('expiring', '即将过期'), ('overstock', '库存过量')], max_length=20, verbose_name='预警类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '库存预警',
                'verbose_name_plural': '库存预警',
            },
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, verbose_name='批次号')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='生产日期')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='过期日期')),
                ('quantity', models.IntegerField(default=0, verbose_name='数量')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='成本价')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.product', verbose_name='商品')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '商品批次',
                'verbose_name_plural': '商品批次',
                'ordering': ['-created_at'],
                'unique_together': {('product', 'batch_number')},
            },
        ),
    ]
