# Generated by Django 6.0.6 on 2026-06-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('DRAFT', '未完成'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消'), ('RETURNED', '已退货')], default='DRAFT', max_length=20, verbose_name='状态'),
        ),
    ]
