# Generated by Django 6.0.6 on 2026-06-19 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_add_sale_returned_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    def create_profiles_for_existing_users(apps, schema_editor):
        User = apps.get_model('auth', 'User')
        UserProfile = apps.get_model('inventory', 'UserProfile')
        for user in User.objects.filter(profile__isnull=True):
            UserProfile.objects.create(user=user)

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('department', models.CharField(blank=True, max_length=50, verbose_name='部门')),
                ('employee_id', models.CharField(blank=True, max_length=50, verbose_name='工号')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户扩展信息',
                'verbose_name_plural': '用户扩展信息',
            },
        ),
        migrations.RunPython(create_profiles_for_existing_users, migrations.RunPython.noop),
    ]
